import { useQuery } from '@tanstack/react-query';
import { chatWithAI } from '@/services/ai/ai.service';

/**
 * A short, factual destination overview generated by the app's AI service.
 * Progressive and non-blocking: Explore is fully usable without it, and any
 * failure (provider down, malformed output) resolves to `brief: null` rather
 * than surfacing an error — the overview block simply doesn't render.
 */
export interface DestinationBrief {
  summary: string;
  knownFor: string[];
  bestTime: string;
}

const SYSTEM_PROMPT =
  'You are a concise India travel expert. For the given Indian destination, respond with ONLY ' +
  'minified JSON (no markdown, no prose) matching exactly: ' +
  '{"summary": string, "knownFor": string[], "bestTime": string}. ' +
  'summary = 2-3 factual sentences orienting a traveller to the place. ' +
  'knownFor = 3 to 5 short highlights, each 1-4 words (landmarks, food, or experiences). ' +
  'bestTime = the best months to visit, short (e.g. "October to March"). ' +
  'Answer for the place as it exists in India. Output nothing outside the JSON object.';

/** Defensively extract the JSON object from a model response and validate its shape. */
function parseBrief(content: string): DestinationBrief {
  const start = content.indexOf('{');
  const end = content.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) {
    throw new Error('destination brief: no JSON object in response');
  }
  const obj = JSON.parse(content.slice(start, end + 1)) as Partial<DestinationBrief>;

  const summary = typeof obj.summary === 'string' ? obj.summary.trim() : '';
  const knownFor = Array.isArray(obj.knownFor)
    ? obj.knownFor
        .filter((x): x is string => typeof x === 'string' && x.trim().length > 0)
        .map((x) => x.trim())
        .slice(0, 5)
    : [];
  const bestTime = typeof obj.bestTime === 'string' ? obj.bestTime.trim() : '';

  if (!summary) throw new Error('destination brief: missing summary');
  return { summary, knownFor, bestTime };
}

export function useDestinationBrief(destination: string | null | undefined): {
  brief: DestinationBrief | null;
  isLoading: boolean;
  isError: boolean;
} {
  const key = destination?.trim() ?? '';
  const enabled = key.length > 0;

  const { data, isLoading, isError, fetchStatus } = useQuery<DestinationBrief, Error>({
    queryKey: ['destination-brief', key.toLowerCase()],
    queryFn: async () => {
      const res = await chatWithAI([{ role: 'user', content: `Destination: ${key}` }], {
        systemPrompt: SYSTEM_PROMPT,
      });
      return parseBrief(res.content);
    },
    enabled,
    // A destination overview is effectively static — cache aggressively so the
    // same place never re-hits the AI service within a session/day.
    staleTime: 24 * 60 * 60 * 1000,
    gcTime: 7 * 24 * 60 * 60 * 1000,
    retry: 1,
  });

  return {
    brief: data ?? null,
    isLoading: enabled && isLoading && fetchStatus !== 'idle',
    isError,
  };
}
